name: FYP AGV project

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 workspace and install dependencies
        shell: bash  # Change the shell from default 'sh' to 'bash'
        run: |
          # Create a ROS 2 workspace directory and its src folder
          mkdir -p ~/ros2_ws/src

          # Source the ROS 2 setup script
          source /opt/ros/humble/setup.bash

          if [ "$(find ~/ros2_ws/src -name 'package.xml' | wc -l)" -gt 0 ]; then
            rosdep update
            rosdep install --from-paths ~/ros2_ws/src --ignore-src -r -y
          else
            echo "No packages found. Skipping dependency installation."
          fi

      - name: Build the ROS 2 workspace
        shell: bash  # Change the shell from default 'sh' to 'bash'
        run: |
          # Source the ROS 2 setup again in this shell session
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws

          # Build using colcon with symlink install enabled (helps during development)
          colcon build --symlink-install
